4-5 modules
js-tasks-ru/jsbasic-20231211_ddre111222 pull request #6
Opened 2024-01-12 16:54 UTC by ddre111

2024-01-12 16:55 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-01-12 16:58 UTC, koalex requested changes
Решение не принимаю. Зачем удалены файлы 6 модуля?

2024-01-12 17:01 UTC, ddre111 commented
Я 6 модуль не делал ещё,хотел запулить два предыдущих, а получилось, что
запулил вместе с ним.

пт, 12 янв. 2024 г. в 19:58, Konstantin Aleksandrov <
***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> Решение не принимаю. Зачем удалены файлы 6 модуля?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/js-tasks-ru/jsbasic-20231211_ddre111222/pull/6#pullrequestreview-1818680108>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BENUSVVFFLQI4DEHVKPFOLTYOFTSNAVCNFSM6AAAAABBYNPZ6CVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQMJYGY4DAMJQHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2024-01-12 17:03 UTC, koalex commented
> Я 6 модуль не делал ещё,хотел запулить два предыдущих, а получилось, что запулил вместе с ним. пт, 12 янв. 2024 г. в 19:58, Konstantin Aleksandrov < ***@***.***>:
> […](#)

придётся сделать иначе если я приму этот ПР то в чистовике они удалятся

2024-01-12 17:06 UTC, ddre111 commented
> > Я 6 модуль не делал ещё,хотел запулить два предыдущих, а получилось, что запулил вместе с ним. пт, 12 янв. 2024 г. в 19:58, Konstantin Aleksandrov < _**@**_.***>:
> > […](#)
> 
> придётся сделать иначе если я приму этот ПР то в чистовике они удалятся

понял тогда скину всё вместе

2024-01-14 16:59 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-01-14 17:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2024-01-15 05:16 UTC, koalex approved these changes

2024-01-15 05:18 UTC, merged